const PRODUCT_INFO = [
  {
    id: 1,
    rating: "4⭐ | 6777",
    product_name: "Lamzu MayaX",
    actual_price: "10,000",
    current_price: "9,000",
    discount_percent: "10",
    image_src: "Images/Lamzu Maya.webp",
    color: "Black",
  },
  {
    id: 2,
    rating: "5⭐ | 1999",
    product_name: "GSR II",
    actual_price: "5,000",
    current_price: "5,000",
    discount_percent: "0",
    image_src: "Images/GSR II.png",
    color: "Black",
  },
  {
    id: 3,
    rating: "5⭐ | 1719",
    product_name: "RTX 4070",
    actual_price: "100,000",
    current_price: "95,000",
    discount_percent: "5",
    image_src: "Images/trx 4070.png",
    color: "Black",
  },
  {
    id: 4,
    rating: "4⭐ | 1134",
    product_name: "WD Black SN770",
    actual_price: "15,000",
    current_price: "15,000",
    discount_percent: "0",
    image_src: "Images/Western Digital WD Black SN770 NVMe 1TB.jpg",
    color: "Black",
  },
  {
    id: 5,
    rating: "5⭐ | 1233",
    product_name: "Truthear Zero",
    actual_price: "3,000",
    current_price: "3,000",
    discount_percent: "0",
    image_src: "Images/Truthear Zero IEM.webp",
    color: "Blue",
  },
  {
    id: 6,
    rating: "5⭐ | 546",
    product_name: "PS5 controller",
    actual_price: "10,000",
    current_price: "9,000",
    discount_percent: "10",
    image_src: "Images/ps5_controller.png",
    color: "White",
  },
  {
    id: 7,
    rating: "5⭐ | 645",
    product_name: "Aula F75",
    actual_price: "7,500",
    current_price: "7,500",
    discount_percent: "0",
    image_src: "Images/Aula F75 Glacie.png",
    color: "White",
  },
  {
    id: 8,
    rating: "5⭐ | 3443",
    product_name: "BENQ Monitor",
    actual_price: "65,000",
    current_price: "58,500",
    discount_percent: "10",
    image_src: "Images/01-xl2540k-xl-.avif",
    color: "Black",
  },
  {
    id: 9,
    rating: "5⭐ | 5666",
    product_name: "Logitech G PRO X",
    actual_price: "22,000",
    current_price: "19,800",
    discount_percent: "10",
    image_src: "Images/Logitech g pro x.png",
    color: "White",
  },
  {
    id: 10,
    rating: "5⭐ | 2234",
    product_name: "RTX 5070TI",
    actual_price: "65,000",
    current_price: "65,500",
    discount_percent: "0",
    image_src: "Images/5070 TI.png",
    color: "Black",
  },
  {
    id: 11,
    rating: "3⭐ | 545",
    product_name: "Redragon E200",
    actual_price: "1,200",
    current_price: "1,350",
    discount_percent: "10",
    image_src: "Images/Redragon E200.png",
    color: "Black",
  },
  {
    id: 12,
    rating: "5⭐ | 3565",
    product_name: "Wooting 60HE",
    actual_price: "30,000",
    current_price: "30,000",
    discount_percent: "0",
    image_src: "Images/wooting 60he.png",
    color: "Black",
  },
];
